# -*- coding: utf-8 -*-
"""data_2_distributions

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ujGAFSaXPkdUgL9gMjL772WBzNjOdVnq
"""

import numpy as np
import pandas as pd

df = pd.read_excel('data_2.xlsx')

print(df)

import matplotlib.pyplot as plt
plt.hist(df['obs'])
plt.show()

df.describe()

stats_labels = ['Mean Observed', 'Variance Observed', 'Skew Observed', 'Kurt Observed']
stats_values = [round(df['obs'].mean(), 2), round(df['obs'].var(), 2), round(df['obs'].skew(),2), round(df['obs'].kurt(),2)]
print(set(zip(stats_labels, stats_values)))

import statsmodels.api as sm
import scipy.stats as stats
from scipy.stats import norm, uniform, poisson
from statsmodels.graphics.gofplots import qqplot

sm.qqplot(df['obs'], stats.uniform, fit = True, line = '45')
plt.show()

import scipy.stats as stats
stats.probplot(df['obs'], dist='uniform', plot=plt)
plt.show()

"""NULL HYPOTHESIS: The given data follows Uniform distribution.

---


ALTERNATE HYPOTHESIS: The given data does not follow Uniform distribution
"""

df['exp'] = 54.925080

df

from scipy.stats import chisquare

chisquare(df['obs'], df['exp'])

from scipy.stats import chi2
chi2.ppf(0.95,49)

