# -*- coding: utf-8 -*-
"""data_3_distributions

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GlNR16G6bLOjJdmS6GMgJ3mnpDCJ_lem
"""

import numpy as np
import pandas as pd

df = pd.read_excel('data_3.xlsx')

print(df)

import matplotlib.pyplot as plt
plt.hist(df['obs'])
plt.show()

df.describe()

stats_labels = ['Mean Observed', 'Variance Observed', 'Skew Observed', 'Kurt Observed']
stats_values = [round(df['obs'].mean(), 2), round(df['obs'].var(), 2), round(df['obs'].skew(),2), round(df['obs'].kurt(),2)]
print(set(zip(stats_labels, stats_values)))

df.median()

import statsmodels.api as sm
import scipy.stats as stats
from scipy.stats import norm
from statsmodels.graphics.gofplots import qqplot

sm.qqplot(df['obs'], line ='45',fit = True)
plt.show()

import scipy.stats as stats
stats.probplot(df['obs'], dist='norm', plot=plt)
plt.show()

"""Let us split the data into 6 equal intervals"""

n = 1/6

import scipy.stats

for i in range(1,6):
  prob_intervals = [scipy.stats.norm.ppf(i*n,df['obs'].mean(), df['obs'].std())]
  print(prob_intervals)

expec_freq = [8,8,8,8,8,8,8,8]

obs_freq = [9,7,9,7,9,7,9,7]

from scipy.stats import chisquare

chisquare(obs_freq, expec_freq)

from scipy.stats import chi2
chi2.ppf(0.95,3)

